### ISSUE TITLE
provide more documentation

### ISSUE THREAD

**Issue by emans841** [joesmithjaffa/jenkins-shell#1]
after i edit shodan api
shodan.php refuses to work
i manaually source for servers on shodan error again

**Comment by joesmithjaffa** [comment]
@emans841 Can you please copy paste the error?

**Comment by TwinTechSolutions** [comment]
remove the $ symbol

**Comment by emans841** [comment]
Making Shodan API request for Page = 1
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 2
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=2): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 3
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkOrFrP7y&query=x-jenkins+200&page=3): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 4
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=4): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 5
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=5): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 6
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=6): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 7
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=7): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 8
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=8): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 9
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=9): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 10
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=10): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 11
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=11): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 12
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=12): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 13
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=13): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 14
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=14): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 15
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=15): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 16
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=16): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 17
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=17): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 18
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=18): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 19
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=19): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 20
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=20): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 21
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=21): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 22
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=22): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 23
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=23): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 24
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=24): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 25
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=25): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 26
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=26): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 27
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=27): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 28
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=28): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 29
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=29): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 30
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=30): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 31
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=31): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 32
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=32): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 33
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=33): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 34
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=34): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 35
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=35): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 36
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=36): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 37
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=37): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 38
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=38): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 39
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=39): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 40
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=40): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 41
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=41): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 42
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=42): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 43
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=43): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 44
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=44): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 45
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=45): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 46
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDrFrP7y&query=x-jenkins+200&page=46): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6SIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 47
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCC7y&query=x-jenkins+200&page=47): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 48
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQCCOrFrP7y&query=x-jenkins+200&page=48): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKhkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 49
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=49): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!



Making Shodan API request for Page = 50
PHP Warning:  file_get_contents(https://api.shodan.io/shodan/host/search?key=Yrs6z5FSIKSvj0hDCCCOrFrP7y&query=x-jenkins+200&page=50): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /root/Desktop/jenkins-shell/shodan.php on line 14
Got the response from Shodan

https://api.shodan.io/shodan/host/search?key=Yrs6zSvj0hkNQd2IDCCCOrFrP7y&query=x-jenkins+200&page=

Something shit happened!!

**Comment by joesmithjaffa** [comment]
Please check your api key in shodan. Copy paste it exactly.

Also if your api key doesn't have credits it can work for only page 1. I'm updating it for more user friendly.

**Comment by joesmithjaffa** [comment]
@emans841 Usually Shodan API key is 32 chars length, yours is different. You can find your shodan key in https://developer.shodan.io/ just above My Account button. See below screenshot.

![image](https://user-images.githubusercontent.com/33636378/37637396-84431e36-2c2d-11e8-8d5e-c0e220504110.png)

**Comment by joesmithjaffa** [comment]
I am closing this issue as shodan api key is wrong. Feel free to open if it still doesn't work. Also i updated code, clone again for better experience.

**Comment by emans841** [comment]
i edited my shodan api here,the api is correct
maybe its because of there is no credit in my shodan account
